spring.application.name=management
server.port=8000

# DataSource Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.info.env.enabled=true
info.app.name= Student Management
info.app.version= 1.0
info.app.description= Spring Boot Demo